apiVersion: v1
kind: Namespace
metadata:
  name: ai-platform
  labels:
    app.kubernetes.io/part-of: ai-platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: inference
  labels:
    app.kubernetes.io/part-of: ai-platform
    purpose: inference-endpoints
