apiVersion: apps/v1
kind: Deployment
metadata:
  name: litellm
  namespace: ai-platform
  labels:
    app: litellm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: litellm
  template:
    metadata:
      labels:
        app: litellm
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: litellm
          image: litellm/litellm:v1.81.9-stable.patch.1
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          args: ["--config", "/app/config.yaml"]
          ports:
            - containerPort: 4000
          env:
            - name: LITELLM_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: litellm-secrets
                  key: master-key
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: litellm-db-credentials
                  key: database-url
            - name: STORE_MODEL_IN_DB
              value: "True"
            - name: LANGFUSE_HOST
              value: "http://langfuse-web.ai-platform.svc.cluster.local:3000"
            - name: LANGFUSE_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: langfuse-litellm-keys
                  key: LANGFUSE_PUBLIC_KEY
                  optional: true
            - name: LANGFUSE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: langfuse-litellm-keys
                  key: LANGFUSE_SECRET_KEY
                  optional: true
          volumeMounts:
            - name: config
              mountPath: /app/config.yaml
              subPath: config.yaml
          readinessProbe:
            httpGet:
              path: /health/liveliness
              port: 4000
            initialDelaySeconds: 10
          livenessProbe:
            httpGet:
              path: /health/liveliness
              port: 4000
            initialDelaySeconds: 30
            periodSeconds: 15
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: "1"
              memory: 1Gi
      volumes:
        - name: config
          configMap:
            name: litellm-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: litellm-config
  namespace: ai-platform
data:
  config.yaml: |
    # Models are registered dynamically via the LiteLLM API (POST /model/new).
    # KRO InferenceEndpoint definitions include a registration Job that
    # auto-registers models when deployed — no manual config needed.
    model_list: []
    litellm_settings:
      success_callback: ["langfuse"]
      failure_callback: ["langfuse"]
    general_settings:
      master_key: os.environ/LITELLM_MASTER_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: litellm
  namespace: ai-platform
spec:
  type: ClusterIP
  selector:
    app: litellm
  ports:
    - port: 4000
      targetPort: 4000
      name: http
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: litellm-db
  namespace: ai-platform
spec:
  serviceName: litellm-db
  replicas: 1
  selector:
    matchLabels:
      app: litellm-db
  template:
    metadata:
      labels:
        app: litellm-db
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: postgres
          image: postgres:16-alpine
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: litellm-db-credentials
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: litellm-db-credentials
                  key: password
            - name: POSTGRES_DB
              value: "litellm"
            - name: PGDATA
              value: "/var/lib/postgresql/data/pgdata"
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: litellm-db
  namespace: ai-platform
spec:
  selector:
    app: litellm-db
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: litellm-db
  namespace: ai-platform
spec:
  podSelector:
    matchLabels:
      app: litellm-db
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: litellm
      ports:
        - protocol: TCP
          port: 5432
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: litellm
  namespace: ai-platform
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: litellm
