apiVersion: kro.run/v1alpha1
kind: InferenceEndpoint
metadata:
  name: mistral-7b-v0-1
  namespace: inference
spec:
  model: "mistralai/Mistral-7B-v0.1"
  gpuCount: 1
  maxModelLen: 8192
  minVramPerGpuGiB: 20
  workerMemory: "18Gi"
  # maxNumSeqs: 64
  minReplicas: 1
  maxReplicas: 2
