apiVersion: kro.run/v1alpha1
kind: InferenceEndpoint
metadata:
  name: nemotron-labs-diffusion-14b
  namespace: inference
spec:
  model: "nvidia/Nemotron-Labs-Diffusion-14B"
  gpuCount: 1
  maxModelLen: 8192
  minVramPerGpuGiB: 36
  workerMemory: "30Gi"
  # maxNumSeqs: 64
  minReplicas: 1
  maxReplicas: 2
