# GPU Operator — Helm-based ArgoCD Application
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gpu-operator
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://helm.ngc.nvidia.com/nvidia
      chart: gpu-operator
      targetRevision: v25.10.1
      helm:
        valueFiles:
          - $values/platform/apps/gpu-operator/helm-values.yaml
    - repoURL: https://github.com/radudobrinescu/ai-platform-eks.git
      targetRevision: main
      ref: values
  destination:
    name: in-cluster
    namespace: gpu-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
