# Langfuse — Helm-based ArgoCD Application
# Secrets are pre-created by Terraform (langfuse-secrets in ai-platform namespace).
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: langfuse
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://langfuse.github.io/langfuse-k8s
      chart: langfuse
      targetRevision: "1.5.20"
      helm:
        valueFiles:
          - $values/platform/apps/langfuse/helm-values.yaml
    - repoURL: https://github.com/radudobrinescu/ai-platform-eks.git
      targetRevision: main
      ref: values
  destination:
    name: local-cluster
    namespace: ai-platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
