# ApplicationSet: auto-discovers workload directories and creates ArgoCD Apps
# SETUP: Replace all instances of YOUR_ORG/ai-platform-gitops.git with your actual repo URL
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: workloads
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - git:
        repoURL: https://github.com/radudobrinescu/ai-platform-eks.git
        revision: main
        directories:
          - path: "workloads/*"
          - path: "workloads/examples"
            exclude: true
  template:
    metadata:
      name: "workload-{{ .path.basename }}"
    spec:
      project: default
      source:
        repoURL: https://github.com/radudobrinescu/ai-platform-eks.git
        targetRevision: main
        path: "{{ .path.path }}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{ .path.basename }}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
