---
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: gpu-inference
spec:
  amiSelectorTerms:
    - alias: al2023@latest
  role: ${role}
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: ${cluster_name}
        Name: ${cluster_name}-private-*
        Environment: ${environment}
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: ${cluster_name}
        Environment: ${environment}
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 200Gi
        volumeType: gp3
        encrypted: true
        throughput: 500
        iops: 6000
  userData: |
    MIME-Version: 1.0
    Content-Type: multipart/mixed; boundary="//"

    --//
    Content-Type: text/x-shellscript; charset="us-ascii"

    #!/bin/bash
    set -euo pipefail
    ARCH=$(uname -m)
    SOCI_VERSION="0.11.0"
    if [ "$ARCH" = "x86_64" ]; then ARCH="amd64"; fi
    curl -sSL -o /tmp/soci.tar.gz \
      "https://github.com/awslabs/soci-snapshotter/releases/download/v$${SOCI_VERSION}/soci-snapshotter-$${SOCI_VERSION}-linux-$${ARCH}-static.tar.gz"
    tar -xzf /tmp/soci.tar.gz -C /usr/local/bin soci-snapshotter-grpc
    rm -f /tmp/soci.tar.gz

    mkdir -p /etc/soci-snapshotter-grpc
    cat > /etc/soci-snapshotter-grpc/config.toml <<'SOCIEOF'
    [puller]
    pull_mode = "parallel-pull-unpack"
    max_concurrent_downloads_per_image = 10
    concurrent_download_chunk_size = "16mb"
    max_concurrent_unpacks_per_image = 10
    discard_unpacked_layers = true
    SOCIEOF

    cat > /etc/systemd/system/soci-snapshotter.service <<'SVCEOF'
    [Unit]
    Description=SOCI Snapshotter
    After=network.target
    Before=containerd.service

    [Service]
    Type=simple
    ExecStart=/usr/local/bin/soci-snapshotter-grpc --config /etc/soci-snapshotter-grpc/config.toml
    Restart=always
    RestartSec=5

    [Install]
    WantedBy=multi-user.target
    SVCEOF

    systemctl daemon-reload
    systemctl enable --now soci-snapshotter

    --//
    Content-Type: application/node.eks.aws

    apiVersion: node.eks.aws/v1alpha1
    kind: NodeConfig
    spec:
      kubelet:
        config:
          imageServiceEndpoint: unix:///run/soci-snapshotter-grpc/soci-snapshotter-grpc.sock
      containerd:
        config: |
          [proxy_plugins.soci]
            type = "snapshot"
            address = "/run/soci-snapshotter-grpc/soci-snapshotter-grpc.sock"
            [proxy_plugins.soci.exports]
              root = "/var/lib/containerd/io.containerd.snapshotter.v1.soci"
          [plugins."io.containerd.grpc.v1.cri".containerd]
            snapshotter = "soci"
            disable_snapshot_annotations = false
            discard_unpacked_layers = false
    --//
  tags:
    karpenter.sh/discovery: ${cluster_name}
    Environment: ${environment}
    workload-type: gpu-inference
---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: gpu-inference
spec:
  weight: 50
  template:
    metadata:
      labels:
        workload-type: gpu-inference
    spec:
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: gpu-inference
      taints:
        - key: nvidia.com/gpu
          effect: NoSchedule
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand"]
        - key: karpenter.k8s.aws/instance-family
          operator: In
          values: ["g5", "g5e", "g6", "g6e", "g7", "g7e"]
        - key: karpenter.k8s.aws/instance-size
          operator: In
          values: ["xlarge", "2xlarge", "4xlarge", "8xlarge", "12xlarge", "16xlarge", "24xlarge", "48xlarge"]
  limits:
    nvidia.com/gpu: "16"
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 300s
    budgets:
      - nodes: "1"
