variable "tfstate_region" {
  description = "region where the terraform state is stored"
  type        = string
  default     = null
}

variable "kms_key_admin_roles" {
  description = "list of role ARNs to add to the KMS policy"
  type        = list(string)
  default     = []

}

variable "tags" {
  description = "Tags to apply to resources"
  type        = map(string)
  default     = {}
}

variable "cluster_config" {
  description = "cluster configurations such as version, public/private API endpoint, and more"
  type        = any
  default     = {}
}

variable "shared_config" {
  description = "Shared configuration across all modules/folders"
  type        = map(any)
  default     = {}
}

variable "docker_hub_username" {
  description = "Docker Hub username for ECR pull-through cache. Set via TF_VAR_docker_hub_username env var."
  type        = string
  default     = ""
  # Not marked sensitive: a sensitive username propagates into for_each in
  # the Karpenter module's node_iam_role_additional_policies map (where the
  # comparison `var.docker_hub_username != ""` decides whether to attach the
  # ECR pull-through policy), which Terraform rejects on plan/destroy. Only
  # the access token below is genuinely a secret.
}

variable "docker_hub_access_token" {
  description = "Docker Hub access token for ECR pull-through cache. Set via TF_VAR_docker_hub_access_token env var."
  type        = string
  default     = ""
  sensitive   = true
}

variable "gitops_repo_url" {
  description = "Git repository URL for ArgoCD to sync the AI platform from. Required when cluster_config.capabilities.gitops is true. Example: https://github.com/my-org/ai-platform.git"
  type        = string
  default     = ""
}

variable "gitops_revision" {
  description = "Git revision (branch, tag, or commit) for ArgoCD to track."
  type        = string
  default     = "main"
}

variable "gitops_workloads_repo_url" {
  description = "Git repository URL for the SELF-SERVICE WORKLOADS (models/, teams/, scale-models/). Leave empty (default) to keep workloads in the same repo as the platform (gitops_repo_url) — simplest, single-repo. Set this to a separate, tenant-owned repo for multi-team self-service, so teams get write access to the workloads repo ONLY (never the platform repo). See workloads/README.md."
  type        = string
  default     = ""
}

variable "enable_cloudfront_edge" {
  description = "Activate the opt-in CloudFront edge: public HTTPS for the platform UIs via CloudFront VPC origins to the INTERNAL ALB (built in Terraform — the managed ACK controller can't create VPC origins). Requires the ALB to already exist, so enable it as a post-up step (`./platformctl edge cloudfront`). Each distribution is billable. The CloudFront domains auto-wire into the Cognito callback URLs. See docs / platformctl edge."
  type        = bool
  default     = false
}

variable "langfuse_nextauth_url" {
  description = "Browser-facing URL of the Langfuse web UI (the Host that NextAuth validates sign-in against). For the default turnkey ALB access you can leave this as-is: the langfuse-nextauth-url CronJob (platform/config/langfuse-nextauth-url.yaml) discovers the ALB hostname at runtime and sets NEXTAUTH_URL on the langfuse-web Deployment automatically. Override only matters if you pin a custom domain — and that is done in platform/services/langfuse/helm-values.yaml (nextauth.url), which the reconciler then respects. This var is retained for reference/back-compat (it feeds the langfuse-init secret's NEXTAUTH_URL key, which the chart does not consume)."
  type        = string
  default     = "http://localhost:3000"
}

variable "langfuse_init_user_email" {
  description = "Email for the Langfuse admin user created on first boot (headless initialization). Used to sign in to the Langfuse UI; the password is generated by Terraform and surfaced as the langfuse_admin_password output."
  type        = string
  default     = "admin@ai-platform.local"
}

variable "enable_bedrock" {
  description = "Expose Amazon Bedrock models (e.g. Claude Sonnet 4.6) through LiteLLM. When true, an IRSA role granting bedrock:InvokeModel is created and attached to the `litellm` ServiceAccount. Requires Bedrock model access to be enabled in-account for the target model (a one-time console toggle). The model itself is declared in platform/services/litellm/litellm.yaml."
  type        = bool
  default     = true
}

variable "gpu_data_volume_snapshot_id" {
  description = "EBS snapshot ID containing the pre-pulled GPU container image (vLLM serving image). Created by ops/image/create-data-volume-snapshot.sh. When set, Karpenter GPU nodes boot with the image already on disk, eliminating the multi-minute image pull."
  type        = string
  default     = ""
}

variable "enable_sso" {
  description = "Ship a Cognito-backed SSO identity plane for the platform UIs (Open WebUI, LiteLLM UI, Langfuse) and per-user cost attribution. When true (and gitops is enabled), Terraform creates a Cognito user pool, hosted-UI domain, groups (admins/developers/users), three seed users (passwords surfaced as outputs), and app clients. SSO works out of the box via `platformctl tunnel` (localhost callbacks); set sso_public_urls once a public HTTPS front (CloudFront) is deployed. Optionally federate an enterprise IdP into the pool. Identity Center remains required only for ArgoCD SSO."
  type        = bool
  default     = true
}

variable "sso_public_urls" {
  description = "Optional public base URLs (e.g. CloudFront) per UI, appended to the Cognito app-client callback/logout URLs. Keys: open-webui, litellm, langfuse, oauth2-proxy. Localhost tunnel callbacks always work out of the box; set these once a public HTTPS front is deployed. Example: { open-webui = \"https://d123.cloudfront.net\" }"
  type        = map(string)
  default     = {}
}
