variable "tfstate_region" {
  description = "region where the terraform state is stored"
  type        = string
  default     = null
}

variable "kms_key_admin_roles" {
  description = "list of role ARNs to add to the KMS policy"
  type        = list(string)
  default     = []

}

variable "tags" {
  description = "Tags to apply to resources"
  type        = map(string)
  default     = {}
}

variable "cluster_config" {
  description = "cluster configurations such as version, public/private API endpoint, and more"
  type        = any
  default     = {}
}

variable "shared_config" {
  description = "Shared configuration across all modules/folders"
  type        = map(any)
  default     = {}
}

variable "docker_hub_username" {
  description = "Docker Hub username for ECR pull-through cache. Set via TF_VAR_docker_hub_username env var."
  type        = string
  default     = ""
  sensitive   = true
}

variable "docker_hub_access_token" {
  description = "Docker Hub access token for ECR pull-through cache. Set via TF_VAR_docker_hub_access_token env var."
  type        = string
  default     = ""
  sensitive   = true
}

variable "gitops_repo_url" {
  description = "Git repository URL for ArgoCD to sync the AI platform from. Required when cluster_config.capabilities.gitops is true. Example: https://github.com/my-org/ai-platform.git"
  type        = string
  default     = ""
}

variable "gitops_revision" {
  description = "Git revision (branch, tag, or commit) for ArgoCD to track."
  type        = string
  default     = "main"
}

variable "enable_fine_tuning" {
  description = "Enable self-service fine-tuning (FineTuneJob). When true, Terraform builds + pushes the Unsloth trainer image to ECR, creates a training-datasets S3 bucket, and provisions the fine-tuning-worker ServiceAccount + IRSA + RBAC. Building the image requires Docker on the apply host (or run ops/build-unsloth-image.sh in CI, then re-apply)."
  type        = bool
  default     = true
}

variable "langfuse_nextauth_url" {
  description = "Browser-facing URL of the Langfuse web UI (the Host that NextAuth validates sign-in against). For the default turnkey ALB access you can leave this as-is: the langfuse-nextauth-url CronJob (platform/config/langfuse-nextauth-url.yaml) discovers the ALB hostname at runtime and sets NEXTAUTH_URL on the langfuse-web Deployment automatically. Override only matters if you pin a custom domain — and that is done in platform/services/langfuse/helm-values.yaml (nextauth.url), which the reconciler then respects. This var is retained for reference/back-compat (it feeds the langfuse-init secret's NEXTAUTH_URL key, which the chart does not consume)."
  type        = string
  default     = "http://localhost:3000"
}

variable "langfuse_init_user_email" {
  description = "Email for the Langfuse admin user created on first boot (headless initialization). Used to sign in to the Langfuse UI; the password is generated by Terraform and surfaced as the langfuse_admin_password output."
  type        = string
  default     = "admin@ai-platform.local"
}

variable "enable_bedrock" {
  description = "Expose Amazon Bedrock models (e.g. Claude Sonnet 4.6) through LiteLLM. When true, an IRSA role granting bedrock:InvokeModel is created and attached to the `litellm` ServiceAccount. Requires Bedrock model access to be enabled in-account for the target model (a one-time console toggle). The model itself is declared in platform/services/litellm/litellm.yaml."
  type        = bool
  default     = true
}

variable "gpu_data_volume_snapshot_id" {
  description = "EBS snapshot ID containing pre-pulled GPU container images (Ray LLM). Created by ops/create-data-volume-snapshot.sh. When set, Karpenter GPU nodes boot with images already on disk, eliminating the multi-minute image pull."
  type        = string
  default     = ""
}
