apiVersion: v1
kind: Secret
metadata:
  name: in-cluster
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: in-cluster
  server: arn:aws:eks:eu-central-1:802019299867:cluster/ai-gitops-gitops-test
  config: |
    {
      "tlsClientConfig": {
        "insecure": false
      }
    }
